"""Real-repository coding harness primitives.

The existing ``lbah.environments.coding_env`` module is a simulated diff
environment for benchmark tasks. This package is the first LBAH-Code slice:
inspect/edit/test/finish actions over an actual workspace, with concern-led
verification and retry feedback.
"""

from .actions import CodingAction, CodingObservation, CodingTask
from .agents import ModelCodingAgent, ScriptedCodingAgent
from .contamination import (
    ContaminationInstance,
    ContaminationProbeResult,
    agent_for,
    generate_slice,
    run_contamination_probe,
    run_contamination_probe_on_real_diff,
)
from .events import CodingEvent, CodingEventLog, events_from_ledger
from .ledger import CodingConcern, CodingLedger
from .official_swebench import (
    ContaminationMarker,
    ContaminationProbeArtifact,
    ContaminationProbePlan,
    DopplerRunConfig,
    OfficialSWEBenchRunPlan,
    OfficialSWEBenchTarget,
    load_official_swebench_command,
    plan_contamination_probe_on_artifacts,
    plan_official_swebench_run,
    run_contamination_probe_on_artifacts,
    run_official_swebench_plan,
)
from .recursive import (
    RecursiveCodingHarnessRunner,
    ScriptedChildAgent,
    apply_child_result,
    validate_child_result,
)
from .runner import CodingHarnessRunner, CodingRunResult
from .swebench import (
    SWEBenchInstance,
    infer_swebench_allowed_paths,
    load_swebench_instances,
    parse_swebench_test_list,
    swebench_run_artifact,
    swebench_test_command,
    swebench_to_coding_task,
    write_swebench_run_artifact,
)
from .swebench_candidates import (
    SWEBenchCandidateMatrixManifest,
    SWEBenchCandidateInstanceOutcome,
    SWEBenchCandidateOfficialInput,
    SWEBenchCandidateRole,
    SWEBenchCandidateSummary,
    SWEBenchOfficialCandidateReport,
    default_swebench_candidate_roles,
    infer_swebench_candidate_id_from_path,
    load_swebench_candidate_matrix_manifest,
    load_swebench_official_candidate_report,
    summarize_swebench_candidate_reports,
    swebench_candidate_id,
    write_swebench_candidate_summary,
    write_swebench_candidate_matrix,
)
from .swebench_eval import (
    SWEBenchBackendKind,
    SWEBenchCacheLevel,
    SWEBenchEvaluationOptions,
    SWEBenchEvaluationResult,
    SWEBenchExecutionBackend,
    SWEBenchFailureKind,
    SWEBenchOfficialHarnessInputs,
    SWEBenchOfficialHarnessSpec,
    SWEBenchPreparedWorkspace,
    SWEBenchSubsetManifest,
    SWEBenchSuiteResult,
    build_swebench_subset_manifests,
    classify_swebench_failure,
    official_swebench_command,
    prepare_swebench_workspace,
    resolve_swebench_repo_source,
    run_swebench_instance,
    run_swebench_smoke_suite,
    run_swebench_tests,
    sanitize_swebench_id,
    summarize_swebench_results,
    swebench_eval_commands,
    swebench_prediction_rows,
    write_official_swebench_inputs,
    write_swebench_evaluation_artifacts,
    write_swebench_predictions,
    write_swebench_subset_manifests,
)
from .task_tree import (
    ChildTaskResult,
    ChildTaskSpec,
    TaskTreeNode,
    default_child_tasks,
)
from .tournament import (
    CandidatePatchTournamentRunner,
    CandidateReviewSignal,
    CandidateRun,
    CandidateScore,
    TournamentRunResult,
    extract_candidate_review_signals,
    score_candidate_result,
    select_winning_candidate,
)
from .workspace import CodingWorkspace

__all__ = [
    "CodingAction",
    "CodingObservation",
    "CodingTask",
    "ScriptedCodingAgent",
    "CodingConcern",
    "CodingLedger",
    "CodingEvent",
    "CodingEventLog",
    "events_from_ledger",
    "ContaminationInstance",
    "ContaminationProbeResult",
    "agent_for",
    "generate_slice",
    "run_contamination_probe",
    "run_contamination_probe_on_real_diff",
    "ContaminationMarker",
    "ContaminationProbeArtifact",
    "ContaminationProbePlan",
    "DopplerRunConfig",
    "OfficialSWEBenchRunPlan",
    "OfficialSWEBenchTarget",
    "load_official_swebench_command",
    "plan_contamination_probe_on_artifacts",
    "plan_official_swebench_run",
    "run_contamination_probe_on_artifacts",
    "run_official_swebench_plan",
    "CodingHarnessRunner",
    "CodingRunResult",
    "SWEBenchInstance",
    "SWEBenchCandidateInstanceOutcome",
    "SWEBenchCandidateMatrixManifest",
    "SWEBenchCandidateOfficialInput",
    "SWEBenchCandidateRole",
    "SWEBenchCandidateSummary",
    "SWEBenchOfficialCandidateReport",
    "default_swebench_candidate_roles",
    "infer_swebench_candidate_id_from_path",
    "load_swebench_candidate_matrix_manifest",
    "load_swebench_official_candidate_report",
    "summarize_swebench_candidate_reports",
    "swebench_candidate_id",
    "write_swebench_candidate_summary",
    "write_swebench_candidate_matrix",
    "parse_swebench_test_list",
    "infer_swebench_allowed_paths",
    "swebench_test_command",
    "swebench_to_coding_task",
    "load_swebench_instances",
    "swebench_run_artifact",
    "write_swebench_run_artifact",
    "SWEBenchExecutionBackend",
    "SWEBenchBackendKind",
    "SWEBenchCacheLevel",
    "SWEBenchFailureKind",
    "SWEBenchEvaluationOptions",
    "SWEBenchPreparedWorkspace",
    "SWEBenchEvaluationResult",
    "SWEBenchSuiteResult",
    "SWEBenchOfficialHarnessSpec",
    "SWEBenchOfficialHarnessInputs",
    "SWEBenchSubsetManifest",
    "sanitize_swebench_id",
    "resolve_swebench_repo_source",
    "prepare_swebench_workspace",
    "run_swebench_instance",
    "run_swebench_smoke_suite",
    "summarize_swebench_results",
    "run_swebench_tests",
    "swebench_eval_commands",
    "swebench_prediction_rows",
    "write_swebench_predictions",
    "official_swebench_command",
    "write_official_swebench_inputs",
    "build_swebench_subset_manifests",
    "write_swebench_subset_manifests",
    "classify_swebench_failure",
    "write_swebench_evaluation_artifacts",
    "CodingWorkspace",
    "ModelCodingAgent",
    "ChildTaskResult",
    "ChildTaskSpec",
    "TaskTreeNode",
    "default_child_tasks",
    "RecursiveCodingHarnessRunner",
    "ScriptedChildAgent",
    "validate_child_result",
    "apply_child_result",
    "CandidatePatchTournamentRunner",
    "CandidateReviewSignal",
    "CandidateRun",
    "CandidateScore",
    "TournamentRunResult",
    "extract_candidate_review_signals",
    "score_candidate_result",
    "select_winning_candidate",
]
